export const GET_BOOK = "[BOOK] GET BOOK";
export const GET_BOOK_BY_ID = "[BOOK] GET BOOK BY ID";
export const ADD_BOOK = "[BOOK] ADD BOOK";
export const UPDATE_BOOK = "[BOOK] UPDATE BOOK";
export const DELETE_BOOK = "[BOOK] DELETE BOOK";
export const ADD_TO_CART = "[BOOK] ADD TO CART";
export const SIGNIN = "[BOOK] SIGNIN"
export const SIGNOUT = "[BOOK] SIGNOUT"
export const SIGNUP = "[BOOK] SIGNUP"
export const PLUS_ORDER = "[BOOK] PLUS_ORDER"
export const MINUS_ORDER = "[BOOK] MINUS_ORDER"
export const PRICE_CART = "[BOOK] PRICE_CART"
export const UPDATE_SALDO = "[BOOK] UPDATE_SALDO"